from .hasSuffix import HasSuffix
from .equalFold import EqualFold
from .isDigit import IsDigit
from .strlen import Strlen
from .isUpper import IsUpper
from .trimLeft import TrimLeft
from .lastIndexAny import LastIndexAny
from .toTitle import ToTitle
from .index import Index
from .trimRight import TrimRight
from .containsStr import ContainsStr
from .toLower import ToLower
from .joinStr import JoinStr
from .trimSuffix import TrimSuffix
from .trim import Trim
from .isLetter import IsLetter
from .toUpper import ToUpper
from .indexAny import IndexAny
from .splitN import SplitN
from .repeat import Repeat
from .lastIndex import LastIndex
from .substring import Substring
from .trimSpace import TrimSpace
from .split import Split
from .splitAfterN import SplitAfterN
from .trimPrefix import TrimPrefix
from .containsAny import ContainsAny
from .splitAfter import SplitAfter
from .replaceAll import ReplaceAll
from .isLower import IsLower
from .hasPrefix import HasPrefix
from .compare import Compare
from .countStr import CountStr
from .title import Title
from .replace import Replace
